#!/bin/sh
# Jeffrey Fulmer <jdfulmer@armstrong.com>
# Sat Jan  6 11:36:27 EST 2001 - initial creation
# Wed Feb 10 19:29:59 EST 2016 - added manifier
#
# part of siege distribution
# automates the autotools
set -x
aclocal 
autoheader
automake --foreign --copy
autoconf
utils/manifier doc/ajping.pod        doc/ajping.1.in        'AJP 1.3 ping utility' 1

